name: deploy-manifests

on:
  push:
    branches: 
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEANTOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-18-6-do-0-sfo2-1598240650611
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
