name: deploy-expiration-2

on:
  push:
    branches: 
      - master
    paths:
      - 'expiration/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t arvindkumar422/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push arvindkumar422/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEANTOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-18-6-do-0-sfo2-1598240650611
      - run: kubectl rollout restart deployment expiration-depl
            
